import { getGameConfig } from './gameConfig.js';
import { getNextDrawInfo } from './drawSchedule.js';
import { scoreCombination, selectPortfolio } from './historyAnalytics.js';
function secureRandom(min,max){const range=max-min+1,maxValid=Math.floor(0x100000000/range)*range,b=new Uint32Array(1);do{crypto.getRandomValues(b)}while(b[0]>=maxValid);return min+(b[0]%range)}
function randomCombination(game){const pool=Array.from({length:game.numberPoolMax},(_,i)=>i+1),out=[];while(out.length<game.numbersToPick)out.push(pool.splice(secureRandom(0,pool.length-1),1)[0]);return out.sort((a,b)=>a-b)}
function humanPattern(c,poolMax){let run=1;for(let i=1;i<c.length;i++){run=c[i]===c[i-1]+1?run+1:1;if(run>=3)return true}const high=c.filter(n=>n>Math.floor(poolMax/2)).length;return high<2||c.filter(n=>n<=31).length>=5}
function baseTicket(gameId,ticket,method,metadata={}){const game=getGameConfig(gameId),draw=getNextDrawInfo(game.id);return{id:crypto.randomUUID(),gameId:game.id,ticket,extra:secureRandom(game.extra.min??1,game.extra.max),createdAt:new Date().toISOString(),...draw,method,metadata,purchased:false,status:'draft'}}
export function generateTicket(gameId,{antiPattern=true}={}){const game=getGameConfig(gameId);let combo=randomCombination(game),attempts=0;while(antiPattern&&humanPattern(combo,game.numberPoolMax)&&attempts++<100)combo=randomCombination(game);return baseTicket(gameId,combo,antiPattern?'crypto-antipattern':'crypto-pure')}
export function generateTicketFromPool(gameId,candidatePool){const game=getGameConfig(gameId);if(!Array.isArray(candidatePool)||candidatePool.length<game.numbersToPick)throw new Error('Pool insufficiente');const pool=[...new Set(candidatePool.map(Number))],out=[];while(out.length<game.numbersToPick)out.push(pool.splice(secureRandom(0,pool.length-1),1)[0]);return baseTicket(gameId,out.sort((a,b)=>a-b),'montecarlo-hotpool')}
export function generateHistoricalTicket(gameId,analysis,{samples=12000}={}){const game=getGameConfig(gameId);if(!analysis?.totalDraws)throw new Error('Storico non disponibile');let best=null;for(let i=0;i<samples;i++){const ticket=randomCombination(game),rated={ticket,...scoreCombination(gameId,ticket,analysis)};if(!best||rated.score>best.score)best=rated}return baseTicket(gameId,best.ticket,'history-ranked',{score:best.score,scoreParts:best.parts,historyDraws:analysis.totalDraws,historyTo:analysis.to})}
export function generatePortfolio(gameId,analysis,count=5,{samples=30000,minDistance=4}={}){const game=getGameConfig(gameId);if(!analysis?.totalDraws)throw new Error('Storico non disponibile');const candidates=[];for(let i=0;i<samples;i++){const ticket=randomCombination(game);candidates.push({ticket,...scoreCombination(gameId,ticket,analysis)})}return selectPortfolio(candidates,Math.max(2,Math.min(Number(count)||5,20)),{minDistance}).map((c,index)=>baseTicket(gameId,c.ticket,'portfolio-optimized',{portfolioIndex:index+1,portfolioSize:count,score:c.score,scoreParts:c.parts,historyDraws:analysis.totalDraws,historyTo:analysis.to}))}
