export const GAMES = {
  bonoloto: {
    id: 'bonoloto',
    name: 'Bonoloto',
    shortName: 'Bonoloto',
    numberPoolMax: 49,
    numbersToPick: 6,
    price: 0.5,
    minimumTicketPrice: 1,
    minSimpleBets: 2,
    maxSimpleBets: 8,
    extra: { key: 'reintegro', label: 'Reintegro', min: 0, max: 9, scope: 'receipt', assignment: 'official-receipt' },
    secondary: null,
    hasComplementary: true,
    drawDays: [0, 1, 2, 3, 4, 5, 6],
    drawTime: { hour: 21, minute: 30 },
    salesCloseTime: { hour: 21, minute: 0 },
    resultPublicationTime: { hour: 21, minute: 50 },
    resultDelayMinutes: 20,
    apiSlug: 'bonoloto',
    accent: 'olive',
    payoff: 'Bote variable',
    supportsMultiple: true,
    multipleSelectionSizes: [5, 7, 8, 9, 10, 11],
  },
  euromillones: {
    id: 'euromillones',
    name: 'Euromillones',
    shortName: 'Euromillones',
    numberPoolMax: 50,
    numbersToPick: 5,
    price: 2.5,
    maxSimpleBets: 5,
    extra: null,
    secondary: {
      key: 'stars',
      label: 'Estrellas',
      singularLabel: 'Estrella',
      min: 1,
      max: 12,
      count: 2,
      scope: 'column',
    },
    hasComplementary: false,
    drawDays: [2, 5],
    drawTime: { hour: 21, minute: 0 },
    salesCloseTime: { hour: 20, minute: 30 },
    resultPublicationTime: { hour: 21, minute: 35 },
    resultDelayMinutes: 35,
    apiSlug: 'euromillones',
    accent: 'blue',
    payoff: 'Bote mínimo garantizado según las reglas vigentes de SELAE',
  },
  gordoprimitiva: {
    id: 'gordoprimitiva',
    name: 'El Gordo de la Primitiva',
    shortName: 'El Gordo',
    numberPoolMax: 54,
    numbersToPick: 5,
    price: 1.5,
    maxSimpleBets: 6,
    extra: { key: 'clave', label: 'Número clave', min: 0, max: 9, scope: 'column' },
    secondary: null,
    hasComplementary: false,
    drawDays: [0],
    drawTime: { hour: 21, minute: 30 },
    salesCloseTime: { hour: 21, minute: 0 },
    resultPublicationTime: { hour: 21, minute: 50 },
    resultDelayMinutes: 20,
    apiSlug: 'gordoprimitiva',
    accent: 'amber',
    payoff: 'Bote variable',
    supportsMultiple: true,
    multipleSelectionSizes: [6, 7],
  },
  eurodreams: {
    id: 'eurodreams',
    name: 'EuroDreams',
    shortName: 'EuroDreams',
    numberPoolMax: 40,
    numbersToPick: 6,
    price: 2.5,
    maxSimpleBets: 6,
    extra: { key: 'sueno', label: 'Sueño', min: 1, max: 5, scope: 'column' },
    secondary: null,
    hasComplementary: false,
    drawDays: [1, 4],
    drawTime: { hour: 21, minute: 0 },
    salesCloseTime: { hour: 20, minute: 30 },
    resultPublicationTime: { hour: 21, minute: 40 },
    resultDelayMinutes: 40,
    apiSlug: 'eurodreams',
    accent: 'violet',
    payoff: '20.000 € al mes durante 30 años',
  },
  primitiva: {
    id: 'primitiva',
    name: 'La Primitiva',
    shortName: 'Primitiva',
    numberPoolMax: 49,
    numbersToPick: 6,
    price: 1,
    maxSimpleBets: 8,
    extra: { key: 'reintegro', label: 'Reintegro', min: 0, max: 9, scope: 'receipt' },
    secondary: null,
    hasComplementary: true,
    drawDays: [1, 4, 6],
    drawTime: { hour: 21, minute: 40 },
    salesCloseTime: { hour: 21, minute: 15 },
    resultPublicationTime: { hour: 22, minute: 0 },
    resultDelayMinutes: 20,
    apiSlug: 'primitiva',
    accent: 'indigo',
    payoff: 'Bote variable',
  },
};

export const DEFAULT_GAME = 'primitiva';

export function getGameConfig(gameId) {
  return GAMES[gameId] || GAMES[DEFAULT_GAME];
}

export function gameRuleSummary(game) {
  if (game.secondary) {
    return `${game.numbersToPick} números del 1 al ${game.numberPoolMax} · ${game.secondary.count} ${game.secondary.label.toLocaleLowerCase('es-ES')} del ${game.secondary.min} al ${game.secondary.max}`;
  }
  if (game.extra?.assignment === 'official-receipt') return `${game.numbersToPick} números del 1 al ${game.numberPoolMax} · reintegro asignado en el resguardo oficial`;
  return `${game.numbersToPick} números del 1 al ${game.numberPoolMax} · ${game.extra.label} del ${game.extra.min} al ${game.extra.max}`;
}
