import React,{useRef,useState}from'react';
import{useGameHistory}from'./hooks/useStorage.js';
import{generateTicket,generateTicketFromPool}from'./utils/engine.js';
import{GAMES,getGameConfig}from'./utils/gameConfig.js';
import{formatDrawDate}from'./utils/drawSchedule.js';
import MonteCarloLab from'./components/MonteCarloLab.jsx';
import HistoryLab from'./components/HistoryLab.jsx';
const MC=20000;
const eur=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'});
function Ball({children,extra=false,hit=false}){return <span className={`w-10 h-10 rounded-full border flex items-center justify-center font-bold ${extra?'bg-amber-300 border-amber-400':hit?'bg-emerald-100 border-emerald-400 text-emerald-800':'bg-slate-100 border-slate-200'}`}>{children}</span>}
function Status({s}){const m={draft:['Bozza','bg-slate-100 text-slate-600'],scheduled:['In attesa','bg-blue-50 text-blue-700'],awaiting_check:['Da verificare','bg-amber-50 text-amber-700'],checked:['Verificata','bg-emerald-50 text-emerald-700']}[s]||['Stato',''];return <span className={`text-[10px] uppercase font-bold px-2 py-1 rounded-full ${m[1]}`}>{m[0]}</span>}
export default function App(){
 const [active,setActive]=useState('eurodreams'),[method,setMethod]=useState('pure'),[latest,setLatest]=useState(null),[busy,setBusy]=useState(false),[checking,setChecking]=useState(false);const worker=useRef();
 const {history,statsByGame,error,saveDraft,saveDrafts,markPurchased,removeTicket,clearHistory,setOfficialPrize,checkResults}=useGameHistory(); const game=getGameConfig(active),items=history.filter(t=>t.gameId===active),stats=statsByGame[active]||{totalSpent:0,totalWon:0,balance:0,unknownPrizes:0};
 const generate=()=>{if(method!=='montecarlo'){const t=generateTicket(active,{antiPattern:method==='antipattern'});saveDraft(t);setLatest(t);return;}setBusy(true);const w=new Worker(new URL('./workers/monteCarlo.worker.js',import.meta.url),{type:'module'});worker.current=w;w.onmessage=({data})=>{if(data.type==='done'){const t=generateTicketFromPool(active,data.hotNumbers);saveDraft(t);setLatest(t);setBusy(false);w.terminate();}};w.postMessage({mode:'hot',totalDraws:MC,poolMax:game.numberPoolMax,pick:game.numbersToPick,topK:game.numbersToPick*3});};
 const check=async()=>{setChecking(true);await checkResults(active);setChecking(false)};
 return <main className="min-h-screen bg-slate-50 text-slate-800 p-4 md:p-8"><div className="max-w-xl mx-auto space-y-6">
  <nav className="flex bg-white p-1.5 rounded-xl border gap-1">{Object.values(GAMES).map(g=><button key={g.id} onClick={()=>{setActive(g.id);setLatest(null)}} className={`flex-1 py-2.5 rounded-lg text-sm font-bold ${active===g.id?'bg-slate-900 text-white':'text-slate-500'}`}>{g.name}</button>)}</nav>
  <header className="bg-white p-6 rounded-2xl border text-center"><h1 className="text-2xl font-black">Primy</h1><p className="text-xs text-slate-400 mb-4">Registro personale · {game.name} · {eur.format(game.price)}</p><div className="grid grid-cols-3 gap-2"><div className="bg-slate-50 p-3 rounded-lg"><small>Spesa reale</small><strong className="block">{eur.format(stats.totalSpent)}</strong></div><div className="bg-slate-50 p-3 rounded-lg"><small>Premi noti</small><strong className="block">{eur.format(stats.totalWon)}</strong></div><div className="bg-slate-50 p-3 rounded-lg"><small>Saldo noto</small><strong className={`block ${stats.balance>=0?'text-emerald-600':'text-rose-600'}`}>{eur.format(stats.balance)}</strong></div></div>{stats.unknownPrizes>0&&<p className="text-xs text-amber-700 mt-3">{stats.unknownPrizes} premio/i con importo non disponibile: esclusi dal saldo.</p>}</header>
  {error&&<div role="alert" className="bg-rose-50 border border-rose-200 text-rose-700 p-4 rounded-xl text-sm">{error}</div>}
  <section className="bg-white p-4 rounded-2xl border"><p className="text-xs font-bold text-slate-400 uppercase mb-3">Generazione</p><div className="grid grid-cols-3 gap-2">{[['pure','Casuale puro'],['antipattern','Anti-pattern'],['montecarlo','Monte Carlo']].map(([id,label])=><button key={id} onClick={()=>setMethod(id)} className={`py-2 rounded-lg text-xs font-semibold border ${method===id?'bg-slate-900 text-white':'border-slate-200'}`}>{label}</button>)}</div><p className="text-[11px] text-slate-500 mt-3">Tutti i metodi hanno la stessa probabilità di vincita. Anti-pattern evita alcune combinazioni popolari; Monte Carlo è solo dimostrativo.</p></section>
  <button onClick={generate} disabled={busy} className="w-full bg-slate-900 text-white font-bold py-4 rounded-xl disabled:opacity-50">{busy?'Simulazione in corso…':`Genera combinazione ${game.name}`}</button>
  {latest&&<section className="bg-white p-6 rounded-2xl border"><div className="flex justify-between"><h2 className="text-sm font-bold text-slate-400 uppercase">Anteprima</h2><Status s={latest.purchased?'scheduled':'draft'}/></div><div className="flex flex-wrap gap-2 justify-center my-4">{latest.ticket.map(n=><Ball key={n}>{n}</Ball>)}<Ball extra>{latest.extra}</Ball></div><p className="text-xs text-center">Estrazione: {formatDrawDate(latest.drawDateISO)}</p>{!latest.purchased&&<button onClick={()=>{markPurchased(latest.id);setLatest({...latest,purchased:true,status:'scheduled'})}} className="w-full mt-4 bg-emerald-600 text-white py-3 rounded-xl font-bold">Segna come acquistata · {eur.format(game.price)}</button>}<p className="text-[11px] text-slate-400 text-center mt-2">La spesa viene conteggiata solo dopo questa conferma.</p></section>}
  <button onClick={check} disabled={checking} className="w-full bg-emerald-100 text-emerald-800 font-bold py-4 rounded-xl disabled:opacity-50">{checking?'Verifica in corso…':'Verifica estrazioni dovute'}</button>
  <section className="bg-white p-5 rounded-2xl border"><div className="flex justify-between items-center mb-4"><h2 className="font-bold">Storico</h2>{items.length>0&&<button onClick={()=>confirm('Cancellare tutto lo storico?')&&clearHistory()} className="text-xs text-rose-600">Cancella tutto</button>}</div>{items.length===0?<p className="text-sm text-slate-400">Nessuna combinazione salvata.</p>:<div className="space-y-3">{items.map(t=>{const wins=new Set(t.result?.winningNumbers||[]);return <article key={t.id} className="border rounded-xl p-4"><div className="flex justify-between items-center"><p className="text-xs font-semibold">{formatDrawDate(t.drawDateISO)}</p><Status s={t.computedStatus}/></div><div className="flex flex-wrap gap-1.5 my-3">{t.ticket.map(n=><Ball key={n} hit={t.status==='checked'&&wins.has(n)}>{n}</Ball>)}<Ball extra>{t.extra}</Ball></div>{t.status==='checked'&&<div className="text-sm bg-slate-50 rounded-lg p-3"><p><strong>{t.prizeCategory||'Nessun premio'}</strong> · {t.matches} numeri</p><p>{t.prizeDisplay}</p>{t.prizeCategory&&t.officialPrize==null&&<label className="block mt-2 text-xs">Inserisci premio ufficiale (€)<input type="number" min="0" step="0.01" className="w-full border rounded p-2 mt-1" onBlur={e=>e.target.value&&setOfficialPrize(t.id,e.target.value)}/></label>}<p className="text-[10px] text-slate-400 mt-2">Fonte risultati: {t.result?.source}</p></div>}<div className="flex gap-2 mt-3">{!t.purchased&&<button onClick={()=>markPurchased(t.id)} className="text-xs bg-emerald-100 px-3 py-2 rounded">Acquistata</button>}<button onClick={()=>removeTicket(t.id)} className="text-xs text-rose-600 px-3 py-2">Elimina</button></div></article>})}</div>}</section>
  <HistoryLab gameId={active} onGenerated={t=>{saveDraft(t);setLatest(t)}} onPortfolio={tickets=>{saveDrafts(tickets);setLatest(tickets[0]||null)}}/>
  <MonteCarloLab gameId={active}/><footer className="text-center text-[11px] text-slate-400 pb-8">Solo per maggiorenni. Nessun metodo aumenta le probabilità di vincita. Gioca responsabilmente.</footer>
 </div></main>;
}
